### PR TITLE
Adding Runtime Folder to docker_folders_create function.

### PR DESCRIPTION
**Pull request by myxptlyk**
Added runtime folder to scope vars (lines 132,138,144) and to the docker_folders_create function (starting line 572)

### CODE REVIEW

**Comment by Drauku** [comment]
Lines 579-580 create the `.env` and `compose.yml` file inside the `../runtime/stackname/`, which I do not think you meant to include.

**Comment by Drauku** [comment]
Also, just a nitpick, lol. In the scope vars list, "runtime" should be last in the list since r comes after c.

**Comment by myxptlyk** [comment]
> Lines 579-580 create the .env and compose.yml file inside the ../runtime/stackname/, which I do not think you meant to include.

Correct.  I should have paid more attention to the code I copied and deciphered it better! 

> Also, just a nitpick, lol. In the scope vars list, "runtime" should be last in the list since r comes after c.

Good call.  I didn't consider that it would be better to be alphabetical, but that makes sense.  In that case, shouldn't configs and compose be switched too?

**Comment by Drauku** [comment]
> Good call. I didn't consider that it would be better to be alphabetical, but that makes sense. In that case, shouldn't configs and compose be switched too?

Which is exactly why I removed that comment and declined to make my suggested change. The current grouping with "paths" at the top and the compose file variable at the bottom is more intuitive, IMHO.

**Pull request merged**
